spring.application.name=projeto1-2026
spring.profiles.active=test
notificador.email.host=smtp.gmail.com

springdoc.api-docs.path=/api-docs

# indica que a transação do BD será encerrada na camada de service.
spring.jpa.open-in-view=true

# nível global da aplicação
#logging.level.root=INFO
# nível específico do Spring
#logging.level.org.springframework=WARN
# nível do seu pacote
#logging.level.com.br.ifmg.produto1_2026=INFO

#logging.level.com.br.ifmg.produto1_2026.resources=ERROR
#logging.level.org.hibernate=ERROR
#logging.file.name=logs/app.log

#logging.pattern.console=%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n

spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:bmatheusgarcia@gmail.com}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# nunca fazer em produção
security.client.id=${CLIENT_ID:myclientid} 
security.client.secret=${CLIENT_SECRET:myclientsecret}

# 1000 * 60 * 24
security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://ifmg.edu.br}