spring.application.name=projeto1-2026
spring.profiles.active=test
notificador.email.host=smtp.gmail.com

# indica que a transação do BD será encerrada na camada de service.
spring.jpa.open-in-view=true