spring.application.name=projeto1-2026
spring.profiles.active=test
notificador.email.host=smtp.gmail.com

springdoc.api-doc.path=/api-docs
# indica que a transação do BD será encerrada na camada de service.
spring.jpa.open-in-view=true

# nível global da aplicação
logging.level.root=INFO
# nível específico do Spring
logging.level.org.springframework=WARN
# nível do seu pacote
logging.level.com.br.ifmg.produto1_2026=INFO

logging.level.com.br.ifmg.produto1_2026.resources=ERROR
logging.level.org.hibernate=ERROR
logging.file.name=logs/app.log

logging.pattern.console=%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n